insert Enfermedad(Nombre)values('Vomito')
insert Enfermedad(Nombre)values('Diarrea')
insert Enfermedad(Nombre)values('Asma')
insert Enfermedad(Nombre)values('Hipertencion')
insert Enfermedad(Nombre)values('Gripe')
insert Enfermedad(Nombre)values('Dengue')
